name: halcyon_lite
description: "A smaller compact version of the finalized Halcyon."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-323.0.dev'

dependencies:
  audioplayers: ^5.1.0
  file_picker: ^5.3.4
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/img/DefaultAA.png
    - assets/moosic/darby-relive.mp3